defaults:
    - dataset: DomainNet
    - _self_
method:
    name: CWCon
    temperature: 0.2
    num_clusters: 7
    cwcon_weight: 1.0
    cwcon_threshold: 0.2
    cwcon_start: 20
    cwcon_warmup: 80
use_mlp_at_val: true
ema: 0.999
batch_size:
    train: 64
    val: 128
optimizer:
    name: SGD
    lr: 0.0002
    momentum: 0.9
    weight_decay: 0.0004
    nesterov: true
scheduler:
    name: CosineAnnealingLR
    T_max: 200
random_seed: 0
max_epochs: 200
