defaults:
    - dataset: DeepFashion
    - _self_
method:
    name: IWCon
    temperature: 0.2
ema: 0.999
batch_size:
    train: 64
    val: 128
optimizer:
    name: SGD
    lr: 0.0002
    momentum: 0.9
    weight_decay: 0.0004
    nesterov: true
scheduler:
    name: CosineAnnealingLR
    T_max: 30
random_seed: 0